packages:
  - "playground"
  - "npm/*"
  - "!npm/vscode-art"
  - "!npm/vscode-vize"
  - "npm/vite-plugin-vize/example"
  - "npm/rspack-vize-plugin/example"
  - "npm/fresco/examples/*"
  - "examples/vite-musea"
  - "docs"
  - "tests"
  - "bench"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
